### ISSUE TITLE
Finalizing scalar functionality

### ISSUE THREAD

**Issue by vpisarev** [4ekmah/loops#8]
The following operations should be added in order to round up the "scalar" part of Loops: 

- [x] load and store operations for any integer type: `int8, uint8, int16, uint16, int32, uint32, int64, uint64`. When the integer size is smaller than the register size (we only support 64 bits currently), the loaded number is expanded to 64 bits by adding 0-bits (`uint*`) or sign bits (`int*`).
- [x] `+, -, *, /`
- [x] unary `-` (negate)
- [x] all comparison operations. *Important: if a comparison is used in 'if', there should be some optimized form: comparison followed by a conditional jump. if a comparison is used as is, e.g. a + (b > c), then a different code should be generated (on Intel there is a family of `setcc` instructions for that)*
- [x] `%` (remainder or modulo, the result should be a signed integer, e.g. when `a < 0, b >= 0 ==> a % b <= 0`)
- [x] `<<, >>, shr` (shift left, shift right and unsigned shift right).
- [x] `&, |, ^, ~` (bitwise and, or, xor, not).
- [x] `min, max, abs, sign`
- [x]  `select(a, b, c)`, i.e. `a ? b : c` without conditional jumps. In C it can be implemented (assuming a=1 or 0) as `int64_t mask =  a-1; int64_t result = b ^ ((b ^ c) & mask)`, but on modern CPUs it can often be implemented more efficiently using specialiazed instructions, e.g. `cmovcc` on Intel.

**Comment by 4ekmah** [comment]
Less than year yet.
